### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by aidylewis** [flood-io/element#101]
**Describe the bug**
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

**To Reproduce**
```typescript
function isStage(url) {
  return url.includes(XXX)
}

export default() => {

  step('News Home page', async browser => {
    const newsHome = 'XXX'
    await browser.visit(newsHome)

    const page = browser.page

    // to ensure we are not on Live
    const pageURL = await page.url()
    assert.ok(pageURL == newsHome)

    const content = await page.content()
    assert.ok(content.includes('news'))

  })

  step('Click Stage links', async browser => {

    const unVisitedLinks = await browser.findElements(By.css('a:link'))
    const hrefs = await Promise.all(unVisitedLinks.map(span => span.getProperty('href')))
    const stageLinks = hrefs.filter(isStage)
    stageLinks.map(async link =>
      await browser.visit(link))
  });
}
```
**Expected behavior**
I'd expect the browser the visit the links in the collection.

**Desktop (please complete the following information):**
 - OS: Fedora 31
 - Node.js version:v 12.14.1
 - Element Version 1.0.8-stable.1

**Comment by aidylewis** [comment]
Improved the code, somewhat:
```typescript
const unVisitedLinks = await browser.findElements(By.css('a:link'))
    const hrefs = await Promise.all(unVisitedLinks.map(span => span.getProperty('href')))
    const stageLinks = hrefs.filter(isStage)

    stageLinks.reduce(async (accPromise: Promise<void>, nextLink) => {

      console.log(nextLink)

      return accPromise.then(() => {
        return browser.visit(nextLink)
      })  
    }, Promise.resolve().catch(console.error))
  })  
```
But getting the error:
```
> Error! An unexpected rejection occurred
  Error: no response
```

**Comment by ivanvanderbyl** [comment]
Hi @aidylewis — I think this is a known issue within Puppeteer, which happens when a URL returns a status > 399. For some reason we don't get back any response body if this happens, hence the no response error.

As a test, can you try this on the latest beta version of Element: `@flood/element-cli@beta`

**Comment by ivanvanderbyl** [comment]
Another thing you can try is explicitly catching the promise failure on `browser.visit().catch(err => {})`

**Comment by aidylewis** [comment]
Installed the beta version and this is now fixed.

**Comment by aidylewis** [comment]
I spoke too soon. I was muffling the error. 
```
  _structured: 'yes',
  wrappedUnstructured: false,
  source: 'browser',
  data: {
    url: 'https://www.stage.bbc.co.uk/news#skip-to-content-link-target',
    _kind: 'net',
    kind: 'http',
    subKind: 'no-response'
  },
  originalError: undefined,
  callContext: 'browser.visit'
```
```
$ element --version
Using local version of Element
1.0.10-beta.42
```

**Comment by aidylewis** [comment]
Not sure why it's hitting the **response == null** condition in browser.ts, when there is clearly a response from that link?
```
curl -I https://www.stage.bbc.co.uk/news#skip-to-content-link-target
HTTP/2 200 
date: Thu, 23 Jan 2020 08:57:15 GMT
content-type: text/html;charset=utf-8
content-length: 628843
nel: {"report_to":"default","max_age":600,"include_subdomains":true,"failure_fraction":0.01}
x-cache-action: MISS
vary: accept-encoding
cache-control: public, stale-while-revalidate=10, max-age=30
x-cache-age: 0
report-to: {"group":"default","max_age":2592000,"endpoints":[{"url":"https://europe-west1-bbc-otg-traf-mgr-bq-prod-4591.cloudfunctions.net/report-endpoint","priority":1}],"include_subdomains":true}
x-mrid: n1
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-msig: d3642b478f34b0e2f92ff028eca43b44
x-frame-options: SAMEORIGIN
x-lb-nocache: true
via: 1.1 BBC-GTM
x-bbc-edge-cache-status: MISS
x-bbc-origin-response-status: 200
server: BBC-GTM
```

**Comment by aidylewis** [comment]
This catches the error, but moves onto the next Promise.
```typescript
 step('Click Stage links', async browser => {

    const unVisitedLinks = await browser.findElements(By.css('a:link'))
    const hrefs = await Promise.all(unVisitedLinks.map(span => span.getProperty('href')))
    const stageLinks = hrefs.filter(isStage)

    await stageLinks.reduce(async (accPromise: Promise<void>, nextLink) => {
    await accPromise
    await wait(3000)
    return browser.visit(nextLink).catch(console.error)

    }, Promise.resolve())
  })  
```

**Comment by phileba** [comment]
@aidylewis Does the issue still persists on `element@1.2.3`?

**Comment by phileba** [comment]
@aidylewis you can try with this simple solution, I think it will resolve your problem:
```
for (let i = 0; i < links.length; i++) {
	const link = links[i]
	const promise = browser.waitForNavigation()
	await browser.visit(link).catch(err => {
		console.log(err.data.code)
	})
	await promise
}
