### ISSUE TITLE
Can't use element init

### ISSUE THREAD

**Issue by femdev** [flood-io/element#39]
**Describe the bug**
On Mac OS High Sierra - get error when trying to use 'element init'

**To Reproduce**
1. On Mac OS High Sierra, run 'brew install flood-io/taps/element'
2. Run element init after install

Result:
➜  Prompt element init
> 'UPDATE AVAILABLE' The latest   version of Element CLI is 1.0.4
> Get it by running yarn global upgrade @flood/element-cli@latest
initting into /Users/elise/Repos/PluginTests
? The title of this test. (PluginTests) > Error! An unexpected empty rejection occurred
 rejection: null
this is a bug, please report it here https://github.com/flood-io/element/issues/new?template=bug_report.md

**Expected behavior**
Expected no error! It claims I already have 1.0.4 if trying to update as well. 

**Screenshots**

**Desktop (please complete the following information):**
Mac OS High Sierra

**Additional context**

**Comment by ivanvanderbyl** [comment]
@femdev did you try updating Element?

**Comment by lachie** [comment]
Could be related to #36 
@femdev we'd need more info on where you're running this from.

**Comment by mohan-ally** [comment]
I am also facing the same issue https://share.getcloudapp.com/NQueX4bK
https://share.getcloudapp.com/X6u265zd

**Comment by dorrogeray** [comment]
I can confirm this issue:

*Desktop:*

OS: Ubuntu 18.04
Node.js version: 12.13
Version 1.0.10-beta.45

**Comment by ivanvanderbyl** [comment]
@dorrogeray sorry about that, it should be fixed in the latest beta `1.0.10-beta.52`

**Comment by skurra** [comment]
How do we download this beta version?

**Comment by ivanvanderbyl** [comment]
With yarn:
```
yarn global upgrade @flood/element-cli@beta
```

or with NPM:
```
npm -g install @flood/element-cli@beta
```

**Comment by linklink36** [comment]
I tried this way but cannot resolve, still getting 
> Error! An unexpected empty rejection occurred
 rejection: null
It's weird that yesterday I can run smoothly, however today I am getting error while uisng same script :(. Any idea?

**Comment by jkroepke** [comment]
I get this on element run, too.

element Version: 1.0.10-beta.63

**Comment by ivanvanderbyl** [comment]
@jkroepke @linklink36 Is this happening when running a test (`element run`) or with another command?

**Comment by linklink36** [comment]
it's when running 'element run script.ts'

**Comment by ivanvanderbyl** [comment]
Thanks, I'll take a look and try to replicate.

**Comment by jkroepke** [comment]
Yep element run.

The test file is maybe unrelated since I get this error even if the whole file is comment out.

**Comment by HieuLeKMS** [comment]
Using brew will now install the latest stable version of Element (1.2.3), this issue should've already been fixed

**Comment by torfmaster** [comment]
This issue re-occurs in element 1.3.7 with node v14. Is this regression?

**Comment by HieuLeKMS** [comment]
@torfmaster I can't seem to reproduce the issue. Could you show me the error that you're getting?

**Comment by torfmaster** [comment]
@HieuLeKMS:

Here's some output:
```
> npx element run XXXX --no-headless

> INFO UPDATE AVAILABLE The latest stable version of element-cli is 1.3.8
> INFO Get it by running yarn global upgrade element-cli@latest
+0s info: workRootPath: XXXXX
+0s info: testDataPath: XXXXX
Running the test with:
- Element v1.3.8
- Node v14.5.0

● Script Compiler █████████████████████████ compiling (0%)  
 

> Error! An unexpected empty rejection occurred
 rejection: null
```
What puzzles me is that the output says that element v1.3.8 is used although my package.json says that 1.3.7 should be used.

**Comment by HieuLeKMS** [comment]
@torfmaster 
I'm guessing that element's version in your package.json is `^1.3.7`, because of the `^`, the latest compatible version will be installed, which is 1.3.8.
And about the error you're getting, updating your global installed element to 1.3.8 should fix it. Update it by running `yarn global upgrade element-cli@latest`. You might also need to uninstall your current global element first.

**Comment by torfmaster** [comment]
> I'm guessing that element's version in your package.json is ^1.3.7, because of the ^, 

I'm actually using "1.3.7" without the ^ so 1.3.8 shouldn't be installed. However, upgrading to 1.3.8 fixes the issue. Thanks for your support.

**Comment by richard015ar** [comment]
I just ran my script with element cli, and stopped it immediately and from that moment I started to get this error.
I restarted my computer and everything worked well. I tried to see if there is a process in background maybe couldn't closed. But nothing strange on my processes list.
Restarting my computer solved this problem in my case.
